### ISSUE TITLE
comentarios avance 2

### ISSUE THREAD

**Issue by AliciaMstt** [MajoMonteverde/ProyectoFinalBioinf2018-II#1]
Muy buenos avances.

Cuida tu formato markdown, lo pusiste todo en negritas al empezar con #### cada línea.

Los análisis de calidad los puedes hacer más fácil y más bonito con fastqc en vez de con FastXtools.

Sí tendrás que poner las referencias, pero en tu trabajo final.

Dices "Anexo" pero en github no lo veo en tu repo. Más allá de que faltó el archivo, te recomiendo que en vez de decir "anexo" (porque en github no se anexan las cosas, como en un correo) que digas "en este script" y pongas en link a algún lugar de tu repo donde viva el script.

**Comment by MajoMonteverde** [comment]
Ya hice las correcciones aquí 
https://github.com/MajoMonteverde/ProyectoFinalBioinf2018-II/blob/master/segundoavance_v1_MajoMonteverde.md

**Comment by AliciaMstt** [comment]
Muy bien. Recuerda usar el sistema de commits para la historia de los archivos, en vez de poner v1 etc
