### ISSUE TITLE
comentarios avances 3 y README

### ISSUE THREAD

**Issue by AliciaMstt** [MajoMonteverde/ProyectoFinalBioinf2018-II#2]
¡Te faltó el README! solo lo mencionas brevemente en tu avance 3. Te pido que antes de la entrega final subas un avance de tu readme para que vea como lo estás escribienod más allá de las carpetas que ya hiciste en tu repo. Esas se ven bien, por cierto.

Sobre esto "Me falta hacer el corte de mi raw data a menos secuencias para poderlas subir a github. Aquí no estoy segura sobre que tanto de datos debo poner en el repositorio. Tengo muchos archivos muy pesados." 

Recuerda que no debes subir tu proyecto a github, sino via wetransfer o algo similar. 

https://github.com/AliciaMstt/BioinfinvRepro/blob/master/TrabajoFinal/Instrucciones_Proyecto_final.md#contenido-del-proyecto-final

**Comment by MajoMonteverde** [comment]
¿Lo que subí no cuenta como README?

**Comment by AliciaMstt** [comment]
No. Un README explica qué hay en cada carpeta, etc. Checa estos por ejemplo http://datadryad.com/resource/doi:10.5061/dryad.f7248
(ojo ahí está dividido por archivo, pero técnicamente es un README completo si los juntas todos).

**Comment by MajoMonteverde** [comment]
Listo! Espero que este mejor así.
